package com.inn.foresight.module.nv.layer3.utils;

public interface NetworkDataFormats {

	int NETWORK_TYPE_2G_ID = 1;
	int NETWORK_TYPE_3G_ID = 2;
	int NETWORK_TYPE_LTE_ID = 3;
	int NETWORK_TYPE_WIFI_ID = 4;

	int NETWORK_2G_RECORD = 26;
	int NETWORK_3G_RECORD = 32;
	int NETWORK_LTE_RECORD = 30;
	int NETWORK_WIFI_RECORD = 26;

	String APPDATA = "APPDATA";
	String DEVICEDATA = "DEVICEDATA";
	String IDLEDATA = "IDLE";

	int APPDATA_RECORD = 4;
	int DEVICEDATA_RECORD = 9;
	int IDLEDATA_RECORD = 4;

	int NETWORK_2G_MNC_INDEX = 4;
	int NETWORK_3G_MNC_INDEX = 4;
	int NETWORK_LTE_MNC_INDEX = 4;

	int NETWORK_2G_MCC_INDEX = 5;
	int NETWORK_3G_MCC_INDEX = 5;
	int NETWORK_LTE_MCC_INDEX = 5;

	int NETWORK_LTE_CELLID_INDEX = 7;

	int NETWORK_2G_OPERATOR_INDEX = 32;
	int NETWORK_3G_OPERATOR_INDEX = 33;
	int NETWORK_LTE_OPERATOR_INDEX = 39;


	String TEST_TYPE_BROWSE = "HTTP Browsing";
	String TEST_TYPE_PING = "Ping";
	String TEST_TYPE_IDLE = "idle";
	String TEST_TYPE_FTP_DOWNLOAD = "FTP_DOWNLOAD";
	String TEST_TYPE_FTP_UPLOAD = "FTP_UPLOAD";
	String TEST_TYPE_HTTP_DOWNLOAD = "HTTP_DOWNLOAD";
	String TEST_TYPE_HTTP_UPLOAD = "HTTP_UPLOAD";
	String TEST_TYPE_HTTP_PACKET_DOWNLOAD="HTTP_PACKET_DOWNLOAD";
	String TEST_TYPE_FTP_PACKET_DOWNLOAD="FTP_PACKET_DOWNLOAD";


	String NETWORK_TYPE_4G = "LTE";
	String NETWORK_TYPE_3G = "3G";
	String NETWORK_TYPE_2G = "2G";
	String NETWORK_TYPE_NONE = "NONE";

	String NETWORK_TYPE_LTE = "LTE";
	String NETWORK_TYPE_WIFI = "WIFI";

	int DOWNLOAD_4G_ID = 1;
	int DOWNLOAD_3G_ID = 2;
	int DOWNLOAD_2G_ID = 3;

	int UPLOAD_4G_ID = 4;
	int UPLOAD_3G_ID = 5;
	int UPLOAD_2G_ID = 6;

	int BROWSE_4G_ID = 7;
	int BROWSE_3G_ID = 8;
	int BROWSE_2G_ID = 9;

	int PING_4G_ID = 10;
	int PING_3G_ID = 11;
	int PING_2G_ID = 12;

	int IDLE_4G_ID = 13;
	int IDLE_3G_ID = 14;
	int IDLE_2G_ID = 15;






	int NETWORK_TYPE_UNKNOWN_ID = 0;

	int ACTIVE_DATA=0;
	int PASSIVE_DATA=1;
	int PASSIVE_SDK_DATA=2;
	int PASSIVE_APP_DATA=3;


	int PASSIVE_NETWORK_INDEX = 0;
	int PASSIVE_SDK_NETWORK_INDEX = 1;
	int PASSIVE_APP_NETWORK_INDEX = 1;

	String IMEI = "imei";
	String DEVICE_OS = "deviceOS";
	String NV_MODULE = "nvModule";
	String BATTERY_LEVEL_AT_START = "batteryLevelAtRestartDevice";
	String BATTERY_LEVEL_AT_STOP = "batteryLevelAtShutdownDevice";
	String DEVICE_START_TIME = "timeAtRestartDevice";
	String DEVICE_STOP_TIME = "timeAtShutdownDevice";
	String VERSION_NAME = "versionName";
	String HTTP_LINK_DOWNLOAD = "HTTP_LINK_DOWNLOAD";
	String HTTP_LINK_UPLOAD = "HTTP_LINK_UPLOAD";
	String FTP_UPLOAD = "FTP_UPLOAD";
	int SCRIPT_INDEX = 2;
	int MAKE_INDEX = 6;
	int MODEL_INDEX = 7;
	int OPERATORNAME_INDEX = 8;
	int OPERATOR_INDEX = 10;
	int APPVERSION_INDEX = 17;
	int ANDROID_VERSION_INDEX = 22;
	String QUICK_TEST = "QUICK_TEST";
	int QUICK_TEST_4G_ID = 20;
	int QUICK_TEST_2G_ID = 22;
	int QUICK_TEST_3G_ID = 21;
	int JITTER_4G_ID = 23;
	int JITTER_3G_ID = 24;
	int JITTER_2G_ID = 25;
	int YOUTUBE_TEST_4G_ID = 26;
	int SMS_TEST_4G_ID = 27;
	int NETWORK_TYPE_NONE_ID = 28;
	int HTTP_LINK_DOWNLOAD_4G_ID = 29;
	int CALL_TEST_4G_ID = 30;
	int ATTACH_DETACH_TEST_4G_ID = 31;

	int NETWORK_TYPE_NONE_HTTP_FTP_DOWNLOAD = 44;
	int HTTP_DOWNLOAD_TEST_NONE_TESTSTATUS_INDEX = 11;


	int HTTP_LINK_DOWNLOAD_3G_ID = 32;
	int HTTP_LINK_UPLOAD_3G_ID = 33;
	int SMS_TEST_3G_ID = 34;
	int YOUTUBE_TEST_3G_ID = 35;
	int ATTACH_DETACH_TEST_3G_ID = 36;
	int CALL_TEST_3G_ID = 37;

	int HTTP_LINK_DOWNLOAD_2G_ID = 38;
	int HTTP_LINK_UPLOAD_2G_ID = 39;
	int SMS_TEST_2G_ID = 40;
	int YOUTUBE_TEST_2G_ID = 41;
	int ATTACH_DETACH_TEST_2G_ID = 42;
	int CALL_TEST_2G_ID = 43;


	int MAX_DL_INDEX = 4;
	int MAX_UL_INDEX = 7;
	int CELLID_INDEX = 13;
	int PCI_4G_INDEX = 16;
	int LAT_4G_INDEX = 21;
	int LONG_4G_INDEX = 22;
	int TIMESTAMP_4G_INDEX = 24;

	int PSC_INDEX = 10;
	int LAT_3G_INDEX = 17;
	int LONG_3G_INDEX = 18;
	int TIMESTAMP_3G_INDEX = 20;
	int LAT_2G_INDEX = 16;
	int LONG_2G_INDEX = 17;
	int TIMESTAMP_2G_INDEX = 19;
	int RESPONSE_TIME_INDEX = 3;
	int BROWSE_LAT_4G_INDEX = 15;
	int BROWSE_LON_4G_INDEX =16;
	int BROWSE_TIMESTAMP_4G_INDEX =  18;
	int BROWSE_LAT_2G_INDEX = 10;
	int BROWSE_LON_2G_INDEX = 11;
	int BROWSE_TIMESTAMP_2G_INDEX = 13;

	int BROWSE_LAT_3G_INDEX = 11;
	int BROWSE_LON_3G_INDEX = 12;
	int BROWSE_TIMESTAMP_3G_INDEX = 14;
	String JITTER = "JITTER|PACKETLOSS";
	int JITTER_INDEX = 4;
	int JITTER_LAT_4G_INDEX = 16;
	int JITTER_LON_4G_INDEX = 17;
	int JITTER_TIMESTAMP_4G_INDEX = 19;

	int JITTER_LAT_3G_INDEX = 12;
	int JITTER_LON_3G_INDEX = 13;
	int JITTER_TIMESTAMP_3G_INDEX = 15;
	int JITTER_LAT_2G_INDEX = 11;
	int JITTER_LON_2G_INDEX = 12;
	int JITTER_TIMESTAMP_2G_INDEX = 14;
	int IMEI_INDEX = 2;
	int LATENCY_QUICK_TEST_INDEX = 9;
	int RSRP_QUICK_TEST_INDEX = 18;
	int SINR_QUICK_TEST_INDEX = 17;
	String YOUTUBE_TEST = "YOUTUBE_TEST";

	String SMS_TEST = "SMS";

	int NONE_LAT_INDEX = 2;
	int NONE_LONG_INDEX = 3;
	int NONE_TIMESTAMP_INDEX = 5;
	int PCI_LOCK_INDEX = 29;
	int BAND_LOCK_INDEX = 27;
	int RAT_LOCK_INDEX = 30;
	int EARFCN_LOCK_INDEX = 28;
	int AVG_DL_INDEX = 5;
	int AVG_UL_INDEX = 8;

	int PCI_LOCK_VALUE_INDEX = 33;
	int BAND_LOCK_VALUE_INDEX = 31;
	int RAT_LOCK_VALUE_INDEX = 34;
	int EARFCN_LOCK_VALUE_INDEX = 32;


	/** New Config Common index Including None. */
	int TESTTYPE_INDEX=0;
	int TIMESTAMP_INDEX = 1;
	int LATITUDE_INDEX = 2;
	int LONGITUDE_INDEX = 3;
	int NETWORK_TYPE_INDEX = 5;
	/** Network Params parameter. */
	int MNC_INDEX = 6;
	int MCC_INDEX = 7;
	int CELL_ID_LTE_INDEX = 8;
	int CELL_ID_INDEX = 8;	
	int CGI_ID_INDEX = 15;
	int ENODEB_ID_INDEX = 16;
	/** LTE Common Param. */
	int TAC_INDEX = 14;
	int PCI_INDEX = 17;
	int SINR_INDEX = 18;
	int RSRP_INDEX = 19;
	int RSRQ_INDEX = 20;
	int RSSI_INDEX = 21;
	int BAND_INDEX = 29;
	int DLEARFCN_INDEX = 28;
	int ULEARFCN_INDEX = 27;
	
	int DL_4G_INDEX = 51;

	int DL_LINK_URL_4G_INDEX = 52;
	int DL_TESTSTATUS_4G_INDEX = 53;
	int DL_FAILURE_CAUSE_4G_INDEX=54;
	int UL_4G_INDEX = 51;
	String LTE = "LTE";
	String _3G = "3G";
	String _2G = "2G";	
	String NONE = "NONE";
	int LTE_BROWSE_INDEX = 52;
	int LTE_JITTER_INDEX = 53;
	int LTE_LATENCY_INDEX = 52;
	int LTE_IMAGE_INDEX = 51;
	int LTE_QUICKTEST_DL_INDEX = 54;
	int LTE_QUICKTEST_UL_INDEX = 57;
	int LTE_QUICKTEST_LATENCY_INDEX = 58;
	int YOUTUBE_URL_4G_INDEX = 58;
	int RESOLUTION_4G_INDEX = 51;
	int TOTAL_BUFFERING_4G_INDEX = 52;
	int DURATION_4G_INDEX = 57;
	int STALLING_4G_INDEX = 54;
	int FREEZING_RATIO_4G_INDEX = 55;
	int SMS_ID_INDEX = 51;
	int SEND_TIME_INDEX = 52;
	int DELIVERED_TIME_INDEX = 53;
	int TOTAL_TIME_INDEX = 54;
	int SMS_STATUS_INDEX = 55;
	int SMS_NE_STATUS_INDEX = 56;
	int HTTP_LINK_STATUS_INDEX = 53;
	String SHORT_CALL_TEST = "SHORT_CALL";
	String LONG_CALL_TEST = "LONG_CALL";
	int OLD_PCI_4G_INDEX = 22;
	int EVENT_CAUSE_4G_INDEX = 25;
	int LTE_PACKETLOSS_INDEX = 52;
	int YOUTUBE_ITERATION_INDEX = 59;
	int DEVICE_ID_INDEX = 35;
	int REMARK_DL_4G_INDEX = 58;
	int NAVIGATION_START_MESSAGE_DL_4G_INDEX=59;
	int NAVIGATION_STOP_MESSAGE_DL_4G_INDEX=60;

	int REMARK_UL_4G_INDEX = 58;
	int NAVIGATION_START_MESSAGE_UL_4G_INDEX=59;
	int NAVIGATION_STOP_MESSAGE_UL_4G_INDEX=60;
	int LTE_BROWSE_REMARK_INDEX = 55;
	int NAVIGATION_START_MESSAGE_BROWSE_4G_INDEX=61;
	int NAVIGATION_STOP_MESSAGE_BROWSE_4G_INDEX=62;

	int LTE_BROWSE_TEST_STATUS_INDEX = 53;
	int LTE_BROWSE_FAILURE_CAUSE_INDEX = 54;
	int LTE_PING_TEST_STATUS_INDEX = 54;
	int LTE_PING_FAILURE_CAUSE_INDEX = 55;
	int LTE_PING_REMARK_INDEX = 56;
	int LTE_PING_NAVIGATION_START_MESSAGE_INDEX=58;
	int LTE_PING_NAVIGATION_STOP_MESSAGE_INDEX=59;

	int LTE_JITTER_NAVIGATION_START_MESSAGE_INDEX=57;
	int LTE_JITTER_NAVIGATION_STOP_MESSAGE_INDEX=58;

	int LTE_QUICKTEST_TEST_STATUS_INDEX = 59;
	int LTE_QUICKTEST_FAILURE_CAUSE_INDEX = 60;
	int LTE_QUICKTEST_REMARK_INDEX = 61;
	int LTE_QUICKTEST_NAVIGATION_START_MESSAGE_INDEX=62;
	int LTE_QUICKTEST_NAVIGATION_STOP_MESSAGE_INDEX=63;

	int LTE_YOUTUBE_TEST_STATUS_INDEX = 60;
	int LTE_YOUTUBE_FAILURE_CAUSE_INDEX = 61;
	int LTE_YOUTUBE_REMARK_INDEX = 62;
	int LTE_YOUTUBE_NAVIGATION_START_MESSAGE_INDEX=63;
	int LTE_YOUTUBE_NAVIGATION_STOP_MESSAGE_INDEX=64;

	int LTE_SMS_TEST_STATUS_INDEX = 57;
	int LTE_SMS_FAILURE_CAUSE_INDEX = 58;
	int LTE_SMS_REMARK_INDEX = 59;
	int LTE_SMS_NAVIGATION_START_MESSAGE_INDEX=61;
	int LTE_SMS_NAVIGATION_STOP_MESSAGE_INDEX=62;

	int REMARK_HTTP_DL_4G_INDEX = 56;
	int LTE_HTTP_DL_NAVIGATION_START_MESSAGE_INDEX=57;
	int LTE_HTTP_DL_NAVIGATION_STOP_MESSAGE_INDEX=58;

	int LTE_CALL_TEST_STATUS_INDEX = 56;
	int LTE_CALL_FAILURE_CAUSE_INDEX = 57;
	int LTE_CALL_REMARK_INDEX = 58;
	int LTE_CALL_NAVIGATION_START_MESSAGE_INDEX=61;
	int LTE_CALL_NAVIGATION_STOP_MESSAGE_INDEX=62;
	int LTE_CALL_PMOS_INDEX=63;

	

	int LTE_IDLE_REMARK_INDEX = 51;
	int LTE_IDLE_NAVIGATION_START_MESSAGE_INDEX=52;
	int LTE_IDLE_NAVIGATION_STOP_MESSAGE_INDEX=53;

	String ATTACH_DETACH_TEST = "ATTACH_DETACH";
	int LTE_ATTACH_TEST_STATUS_INDEX = 53;
	int LTE_ATTACH_FAILURE_CAUSE_INDEX = 54;
	int LTE_ATTACH_REMARK_INDEX = 55;
	int LTE_ATTACH_NAVIGATION_START_MESSAGE_INDEX=56;
	int LTE_ATTACH_NAVIGATION_STOP_MESSAGE_INDEX=57;

	int YOUTUBE_DL_4G_INDEX = 53;
	int LTE_PING_PACKETLOSS_INDEX = 57;
	int NAVIGATION_START_MESSAGE_PING_4G_INDEX=58;
	int NAVIGATION_STOP_MESSAGE_PING_4G_INDEX=59;
	int BUFFER_SIZE_MESSAGE_PING_4G_INDEX=60;


	int WPT_DNS_RESOLVE_TIME = 58;
	int WPT_URL_TIME = 56;
	int TESTSTATUS_DL_4G_INDEX = 56;
	int FAILURE_CAUSE_DL_4G_INDEX = 57;
	int TESTSTATUS_UL_4G_INDEX = 56;
	int FAILURE_CAUSE_UL_4G_INDEX = 57;
	int BROWSE_URL_LTE_INDEX = 51;
	int HTTP_LINK_FAILURE_CAUSE_4G_INDEX = 54;
	int YOUTUBE_LOAD_TIME_DL_4G_INDEX = 56;
	int MOBILE_NUMBER_INDEX = 21;

	int SMS_DIAL_NUMBER_INDEX=60;
	int HTTP_DOWNLOAD_ATTEMPT_INDEX = 55;
	int HTTP_DOWNLOAD_FAILURE_INDEX = 54;
	int HTTP_DOWNLOAD_SUCCESS_INDEX = 53;
	int HTTP_DOWNLOAD_TIME_INDEX = 52;
	String ATTACH_TEST = "ATTACH";
	String DETACH_TEST = "DETACH";


	int HTTP_DOWNLOAD_ATTEMPT_INDEX_NONE = 10;

	/** 3G Common Param. */
	int PSC_3G_INDEX = 14;
	int LAC_3G_INDEX = 15;
	int RSCP_3G_INDEX = 16;
	int ECNO_3G_INDEX = 17;
	int ECIO_3G_INDEX = 18;


	/** 2G Commmon Param. */
	int LAC_2G_INDEX = 14;
	int RX_QUALITY_2G_INDEX = 15;
	int RX_LEVEL_2G_INDEX = 16;
	int ARFCN_2G_INDEX = 17;

	/** Dl test 3g. */
	int DL_3G_INDEX = 28;
	int REMARK_DL_3G_INDEX = 35;
	int TESTSTATUS_DL_3G_INDEX = 33;
	int FAILURE_CAUSE_DL_3G_INDEX = 34;
	int HTTP_DOWNLOAD_ATTEMPT_3G_INDEX = 32;
	int HTTP_DOWNLOAD_SUCCESS_3G_INDEX = 30;
	int HTTP_DOWNLOAD_FAILURE_3G_INDEX = 31;	
	int HTTP_DOWNLOAD_TIME_3G_INDEX = 29;
	int NAVIGATION_START_MESSAGE_DL_3G_INDEX=36;
	int NAVIGATION_STOP_MESSAGE_DL_3G_INDEX=37;



	/** Dl test 2g. */
	int DL_2G_INDEX = 30;
	int REMARK_DL_2G_INDEX = 37;
	int TESTSTATUS_DL_2G_INDEX = 35;
	int FAILURE_CAUSE_DL_2G_INDEX = 36;
	int HTTP_DOWNLOAD_ATTEMPT_2G_INDEX = 34;
	int HTTP_DOWNLOAD_SUCCESS_2G_INDEX = 32;
	int HTTP_DOWNLOAD_FAILURE_2G_INDEX = 33;	
	int HTTP_DOWNLOAD_TIME_2G_INDEX = 31;
	int NAVIGATION_START_MESSAGE_DL_2G_INDEX=38;
	int NAVIGATION_STOP_MESSAGE_DL_2G_INDEX=39;


	/** Ul test 3g. */
	int UL_3G_INDEX = 28;
	int REMARK_UL_3G_INDEX = 35;
	int TESTSTATUS_UL_3G_INDEX = 33;
	int FAILURE_CAUSE_UL_3G_INDEX = 34;
	int HTTP_UPLOAD_ATTEMPT_3G_INDEX = 32;
	int HTTP_UPLOAD_SUCCESS_3G_INDEX = 30;
	int HTTP_UPLOAD_FAILURE_3G_INDEX = 31;		
	int HTTP_UPLOAD_TIME_3G_INDEX = 29;


	/** Ul test 2g. */
	int UL_2G_INDEX = 30;
	int REMARK_UL_2G_INDEX = 37;
	int TESTSTATUS_UL_2G_INDEX = 35;
	int FAILURE_CAUSE_UL_2G_INDEX = 36;
	int HTTP_UPLOAD_ATTEMPT_2G_INDEX = 34;
	int HTTP_UPLOAD_SUCCESS_2G_INDEX = 32;
	int HTTP_UPLOAD_FAILURE_2G_INDEX = 33;		
	int HTTP_UPLOAD_TIME_2G_INDEX = 31;
	int NAVIGATION_START_MESSAGE_UL_2G_INDEX=38;
	int NAVIGATION_STOP_MESSAGE_UL_2G_INDEX=39;


	/** Browse test 3g. */
	int BROWSE_URL_3G_INDEX = 28;
	int BROWSE_3G_INDEX = 29;
	int BROWSE_TEST_STATUS_3G_INDEX = 30;
	int BROWSE_FAILURE_CAUSE_3G_INDEX = 31;	
	int BROWSE_REMARK_3G_INDEX = 32;
	int WPT_URL_TIME_3G_INDEX = 33;
	int WPT_DNS_RESOLVE_TIME_3G_INDEX = 35;
	int NAVIGATION_START_MESSAGE_BROWSE_3G_INDEX=38;
	int NAVIGATION_STOP_MESSAGE_BROWSE_3G_INDEX=39;



	/** Browse test 2g. */
	int BROWSE_URL_2G_INDEX = 30;
	int BROWSE_2G_INDEX = 31;
	int BROWSE_TEST_STATUS_2G_INDEX = 32;
	int BROWSE_FAILURE_CAUSE_2G_INDEX = 33;	
	int BROWSE_REMARK_2G_INDEX = 34;
	int WPT_URL_TIME_2G_INDEX = 35;
	int WPT_DNS_RESOLVE_TIME_2G_INDEX = 37;
	int NAVIGATION_START_MESSAGE_BROWSE_2G_INDEX=40;
	int NAVIGATION_STOP_MESSAGE_BROWSE_2G_INDEX=41;


	/** PING TEST 3G. */
	int PING_TEST_STATUS_3G_INDEX = 31;
	int PING_FAILURE_CAUSE_3G_INDEX = 32;
	int PING_REMARK_3G_INDEX = 33;
	int LATENCY_3G_INDEX = 29;
	int PING_PACKETLOSS_3G_INDEX = 34;
	int PING_NAVIGATION_START_MESSAGE__3G_INDEX=35;
	int PING_NAVIGATION_STOP_MESSAGE_3G_INDEX=36;
	int BUFFER_SIZE_MESSAGE_PING_3G_INDEX=37;



	/** PING TEST 2G. */
	int PING_TEST_STATUS_2G_INDEX = 33;
	int PING_FAILURE_CAUSE_2G_INDEX = 34;
	int PING_REMARK_2G_INDEX = 35;
	int LATENCY_2G_INDEX = 31;
	int PING_PACKETLOSS_2G_INDEX = 36;
	int PING_NAVIGATION_START_MESSAGE__2G_INDEX=37;
	int PING_NAVIGATION_STOP_MESSAGE_2G_INDEX=38;
	int BUFFER_SIZE_MESSAGE_PING_2G_INDEX=39;


	/** JITTER TEST 3G. */
	int JITTER_3G_INDEX = 30;
	int JITTER_PACKETLOSS_3G_INDEX = 29;
	int JITTER_TEST_STATUS_3G_INDEX = 31;
	int JITTER_FAILURE_CAUSE_3G_INDEX = 32;
	int JITTER_REMARK_3G_INDEX = 33;
	int JITTER_NAVIGATION_START_MESSAGE__3G_INDEX=34;
	int JITTER_NAVIGATION_STOP_MESSAGE_3G_INDEX=35;

	/** JITTER TEST 2G. */
	int JITTER_2G_INDEX = 32;
	int JITTER_PACKETLOSS_2G_INDEX = 31;
	int JITTER_TEST_STATUS_2G_INDEX = 33;
	int JITTER_FAILURE_CAUSE_2G_INDEX = 34;
	int JITTER_REMARK_2G_INDEX = 35;
	int JITTER_NAVIGATION_START_MESSAGE__2G_INDEX=36;
	int JITTER_NAVIGATION_STOP_MESSAGE_2G_INDEX=37;


	/** QUICK TEST 3G. */
	int QUICKTEST_TEST_STATUS_3G_INDEX = 36;
	int QUICKTEST_FAILURE_CAUSE_3G_INDEX = 37;
	int QUICKTEST_REMARK_3G_INDEX = 38;
	int QUICKTEST_IMAGE_3G_INDEX = 28;
	int QUICKTEST_NAVIGATION_START_MESSAGE_3G_INDEX=39;
	int QUICKTEST_NAVIGATION_STOP_MESSAGE_3G_INDEX=40;


	/** QUICK TEST 2G. */
	int QUICKTEST_TEST_STATUS_2G_INDEX = 38;
	int QUICKTEST_FAILURE_CAUSE_2G_INDEX = 39;
	int QUICKTEST_REMARK_2G_INDEX = 40;
	int QUICKTEST_IMAGE_2G_INDEX = 30;
	int QUICKTEST_NAVIGATION_START_MESSAGE_2G_INDEX=41;
	int QUICKTEST_NAVIGATION_STOP_MESSAGE_2G_INDEX=42;


	/** Youtube test 3g. */

	int YOUTUBE_TEST_STATUS_3G_INDEX = 37;
	int YOUTUBE_FAILURE_CAUSE_3G_INDEX = 38;
	int YOUTUBE_REMARK_3G_INDEX = 39;	
	int RESOLUTION_3G_INDEX =28 ;
	int TOTAL_BUFFERING_3G_INDEX = 29;
	int YOUTUBE_DL_3G_INDEX =30;	
	int STALLING_3G_INDEX = 31;
	int FREEZING_RATIO_3G_INDEX = 32;
	int YOUTUBE_LOAD_TIME_DL_3G_INDEX = 33;
	int DURATION_3G_INDEX = 34;
	int YOUTUBE_URL_3G_INDEX = 35;
	int YOUTUBE_ITERATION_3G_INDEX = 36;
	int YOUTUBE_NAVIGATION_START_MESSAGE_3G_INDEX=40;
	int YOUTUBE_NAVIGATION_STOP_MESSAGE_3G_INDEX=41;



	/** Youtube test 2g. */

	int YOUTUBE_TEST_STATUS_2G_INDEX = 39;
	int YOUTUBE_FAILURE_CAUSE_2G_INDEX = 40;
	int YOUTUBE_REMARK_2G_INDEX = 41;	
	int RESOLUTION_2G_INDEX =30 ;
	int TOTAL_BUFFERING_2G_INDEX = 31;
	int YOUTUBE_DL_2G_INDEX =32;	
	int STALLING_2G_INDEX = 33;
	int FREEZING_RATIO_2G_INDEX = 34;
	int YOUTUBE_LOAD_TIME_DL_2G_INDEX = 35;
	int DURATION_2G_INDEX = 36;
	int YOUTUBE_URL_2G_INDEX = 37;
	int YOUTUBE_ITERATION_2G_INDEX = 38;
	int YOUTUBE_NAVIGATION_START_MESSAGE_2G_INDEX=42;
	int YOUTUBE_NAVIGATION_STOP_MESSAGE_2G_INDEX=43;


	/** Sms test 3g. */
	int SMS_TEST_STATUS_3G_INDEX = 34;
	int SMS_FAILURE_CAUSE_3G_INDEX = 35;
	int SMS_REMARK_3G_INDEX = 36;
	int SMS_ID_3G_INDEX = 28;
	int SEND_TIME_3G_INDEX = 29;
	int DELIVERED_TIME_3G_INDEX = 30;
	int TOTAL_TIME_3G_INDEX = 31;
	int SMS_STATUS_3G_INDEX = 32;
	int SMS_NE_STATUS_3G_INDEX = 33;
	int SMS_DIAL_NUMBER_3G_INDEX=37;
	int SMS_NAVIGATION_START_MESSAGE_3G_INDEX=38;
	int SMS_NAVIGATION_STOP_MESSAGE_3G_INDEX=39;



	/** Sms test 2g. */
	int SMS_TEST_STATUS_2G_INDEX = 36;
	int SMS_FAILURE_CAUSE_2G_INDEX = 37;
	int SMS_REMARK_2G_INDEX = 38;
	int SMS_ID_2G_INDEX = 30;
	int SEND_TIME_2G_INDEX = 31;
	int DELIVERED_TIME_2G_INDEX = 32;
	int TOTAL_TIME_2G_INDEX = 33;
	int SMS_STATUS_2G_INDEX = 34;
	int SMS_NE_STATUS_2G_INDEX = 35;
	int SMS_DIAL_NUMBER_2G_INDEX=39;
	int SMS_NAVIGATION_START_MESSAGE_2G_INDEX=40;
	int SMS_NAVIGATION_STOP_MESSAGE_2G_INDEX=41;



	/** HTTP_LINK_DOWNLOAD_3G test. */
	int HTTP_LINK_STATUS_3G_INDEX = 30;
	int HTTP_LINK_FAILURE_CAUSE_3G_INDEX = 31;
	int REMARK_HTTP_DL_3G_INDEX = 33;
	int HTTP_TOTAL_TIME_TAKEN_FOR_3G = 32;
	int HTTP_DL_NAVIGATION_START_MESSAGE_3G_INDEX=34;
	int HTTP_DL_NAVIGATION_STOP_MESSAGE_3G_INDEX=35;



	/** HTTP_LINK_DOWNLOAD_2G test. */
	int HTTP_LINK_STATUS_2G_INDEX = 32;
	int HTTP_LINK_FAILURE_CAUSE_2G_INDEX = 33;
	int REMARK_HTTP_DL_2G_INDEX = 35;
	int HTTP_TOTAL_TIME_TAKEN_FOR_2G = 34;
	int HTTP_DL_NAVIGATION_START_MESSAGE_2G_INDEX=36;
	int HTTP_DL_NAVIGATION_STOP_MESSAGE_2G_INDEX=37;



	/** CALL TEST 3G. */
	int CALL_TEST_STATUS_3G_INDEX = 33;
	int CALL_FAILURE_CAUSE_3G_INDEX = 34;
	int CALL_REMARK_3G_INDEX = 35;
	int CALL_NAVIGATION_START_MESSAGE_3G_INDEX=38;
	int CALL_NAVIGATION_STOP_MESSAGE_3G_INDEX=39;
	int CALL_PMOS_3G_INDEX=40;



	/** CALL TEST 2G. */
	int CALL_TEST_STATUS_2G_INDEX = 35;
	int CALL_FAILURE_CAUSE_2G_INDEX = 36;
	int CALL_REMARK_2G_INDEX = 37;
	int CALL_NAVIGATION_START_MESSAGE_2G_INDEX=40;
	int CALL_NAVIGATION_STOP_MESSAGE_2G_INDEX=41;
	int CALL_PMOS_2G_INDEX=42;



	/** IDLE TEST 3G. */
	int IDLE_REMARK_3G_INDEX = 28;
	int IDLE_NAVIGATION_START_MESSAGE_3G_INDEX=29;
	int IDLE_NAVIGATION_STOP_MESSAGE_3G_INDEX=30;

	/** IDLE TEST 2G. */
	int IDLE_REMARK_2G_INDEX = 30;
	int IDLE_NAVIGATION_START_MESSAGE_2G_INDEX=31;
	int IDLE_NAVIGATION_STOP_MESSAGE_2G_INDEX=32;

	/** ATTACH DETTACH TEST 3G. */
	int ATTACH_TEST_STATUS_3G_INDEX = 30;
	int ATTACH_FAILURE_CAUSE_3G_INDEX = 31;
	int ATTACH_REMARK_3G_INDEX = 32;
	int ATTACH_NAVIGATION_START_MESSAGE_3G_INDEX=33;
	int ATTACH_NAVIGATION_STOP_MESSAGE_3G_INDEX=34;

	/** ATTACH DETTACH TEST 2G. */
	int ATTACH_TEST_STATUS_2G_INDEX = 32;
	int ATTACH_FAILURE_CAUSE_2G_INDEX = 33;
	int ATTACH_REMARK_2G_INDEX = 34;
	int ATTACH_NAVIGATION_START_MESSAGE_2G_INDEX=35;
	int ATTACH_NAVIGATION_STOP_MESSAGE_2G_INDEX=36;



	int TOTAL_DISTANCE_INDEX = 10;
	int BATTARY_INFO_INDEX = 25;
	int CHIPSET_INFO_INDEX = 36;
	int DRIVE_VERSION_INDEX = 24;
	
	int THRESHHOLD_CAUSE_INDEX=37;
	int RSRP_THRESHOLD_VALUE_INDEX=38;	
	int SINR_THRESHOLD_VALUE_INDEX=39;


}
