package com.inn.foresight.core.security.spring.context;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

/**
 * This class is responsible for providing the Spring ApplicationContext object.
 * It implements ApplicationContextAware interface and so, is notified of the
 * ApplicationContext that it runs in.
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 * 
 */
public class ContextProvider implements ApplicationContextAware {

	/** The app context. */
	private static ApplicationContext appContext;

	/**
	 * Sets the application context.
	 *
	 * @param appContext the new application context
	 * @throws BeansException the beans exception
	 */
	public void setApplicationContext(ApplicationContext appContext) {
		this.appContext = appContext;

	}

	/**
	 * Getter for the Application Context Object.
	 *
	 * @return ApplicationContext
	 */
	public static ApplicationContext getContext() {
		return appContext;
	}
}
