package com.inn.foresight.core.generic.exceptions;

/**
 * Represents the exception which is thrown when encountering an error due to
 * system configuration.
 * 
 * @author Auto Generated By HeadStart
 * @version 1.0
 * 
 */
@SuppressWarnings("serial")
public class SystemConfigurationException extends RuntimeException {

	/**
	 * Instantiates a new system configuration exception.
	 */
	public SystemConfigurationException() {
		super();
	}

	/**
	 * Instantiates a new system configuration exception.
	 *
	 * @param message the message
	 * @param cause the cause
	 */
	public SystemConfigurationException(String message, Throwable cause) {
		super(message, cause);
	}

	/**
	 * Instantiates a new system configuration exception.
	 *
	 * @param message the message
	 */
	public SystemConfigurationException(String message) {
		super(message);
	}

	/**
	 * Instantiates a new system configuration exception.
	 *
	 * @param cause the cause
	 */
	public SystemConfigurationException(Throwable cause) {
		super(cause);
	}

}
