package com.inn.foresight.core.kpicomparison.utils;

public interface KpiComparisonConstants {

	String TABLE_MORPHOLOGY_BOUNDARY = "MORPHOLOGY_BOUNDARY_TABLE";
	String MORPHOLOGY_BOUNDARY_COLUMN_FAMILY = "MORPHOLOGY_BOUNDARY_COLUMN_FAMILY";
	String MORPHOLOGY_BOUNDARY_COLUMN_NAME = "MORPHOLOGY_BOUNDARY_COLUMN_NAME";
	public static final String MORPHOLOGY_BOUNDARY_COLORS = "MORPHOLOGY_BOUNDARY_COLORS";
	public static final String KEY_TO_GET_ZONE = "TILE_TO_ZONE_MAP";
}
