package com.inn.foresight.core.generic.exceptions.application;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.ext.ExceptionMapper;

/**
 * The Class ForesightExceptionMapper.
 *
 * @author Autogenerated by Headstart
 * @version 1.0
 */
public class ForesightExceptionMapper implements ExceptionMapper<ForesightException> {

	/**
	 * To response.
	 *
	 * @param exception the exception
	 * @return the response
	 */
	@Override
	public Response toResponse(ForesightException exception) {

		return Response.status(Status.OK).type(MediaType.APPLICATION_JSON).entity(exception.getMessage()).build();
	}

}